const Companies = [
  { value: "3M" },
  { value: "A.O. Smith" },
  { value: "Abbott Laboratories" },
  { value: "AbbVie" },
  { value: "Accenture plc" },
  { value: "Activision Blizzard" },
  { value: "Acuity Brands" },
  { value: "Adobe Systems" },
  { value: "Advance Auto Parts" },
  { value: "Advanced Micro Devices" },
  { value: "AES" },
  { value: "Aetna" },
  { value: "Affiliated Managers Group" },
  { value: "AFLAC" },
  { value: "Agilent Technologies" },
  { value: "Air Products & Chemicals" },
  { value: "Alaska Air Group" },
  { value: "Akamai Technologies" },
  { value: "Albemarle" },
  { value: "Alexandria Real Estate Equities" },
  { value: "Alexion Pharmaceuticals" },
  { value: "Align Technology" },
  { value: "Allegion" },
  { value: "Allergan Plc" },
  { value: "Alliance Data Systems" },
  { value: "Alliant Energy" },
  { value: "Allstate" },
  { value: "Alphabet" },
  { value: "Altria Group" },
  { value: "Amazon" },
  { value: "Ameren" },
  { value: "American Airlines Group" },
  { value: "American Electric Power" },
  { value: "American Express" },
  { value: "American International Group" },
  { value: "American Tower Corp A" },
  { value: "American Water Works" },
  { value: "Ameriprise Financial" },
  { value: "AmerisourceBergen" },
  { value: "AMETEK" },
  { value: "Amgen" },
  { value: "Amphenol" },
  { value: "Anadarko Petroleum" },
  { value: "Analog Devices" },
  { value: "Andeavor" },
  { value: "ANSYS" },
  { value: "Anthem" },
  { value: "Aon plc" },
  { value: "Apache Corporation" },
  { value: "Apartment Investment & Management" },
  { value: "Apple" },
  { value: "Applied Materials" },
  { value: "Aptiv Plc" },
  { value: "Archer-Daniels-Midland" },
  { value: "Arconic" },
  { value: "Arthur J. Gallagher & Co." },
  { value: "Assurant" },
  { value: "AT&T" },
  { value: "Autodesk" },
  { value: "Automatic Data Processing" },
  { value: "AutoZone" },
  { value: "AvalonBay Communities" },
  { value: "Avery Dennison" },
  { value: "Baker Hughes" },
  { value: "Ball" },
  { value: "Bank of America" },
  { value: "Baxter International" },
  { value: "BB&T Corporation" },
  { value: "Becton Dickinson" },
  { value: "Berkshire Hathaway" },
  { value: "Best Buy" },
  { value: "Biogen" },
  { value: "BlackRock" },
  { value: "Block H&R" },
  { value: "Boeing" },
  { value: "Booking Holdings" },
  { value: "BorgWarner" },
  { value: "Boston Properties" },
  { value: "Boston Scientific" },
  { value: "Brighthouse Financial" },
  { value: "Bristol-Myers Squibb" },
  { value: "Broadcom" },
  { value: "Brown-Forman" },
  { value: "C. H. Robinson Worldwide" },
  { value: "Cabot Oil & Gas" },
  { value: "Cadence Design Systems" },
  { value: "Campbell Soup" },
  { value: "Capital One Financial" },
  { value: "Cardinal Health" },
  { value: "Carmax" },
  { value: "Carnival" },
  { value: "Caterpillar" },
  { value: "Cboe Global Markets" },
  { value: "CBRE Group" },
  { value: "CBS" },
  { value: "Celgene" },
  { value: "Centene Corporation" },
  { value: "CenterPoint Energy" },
  { value: "CenturyLink" },
  { value: "Cerner" },
  { value: "CF Industries Holdings" },
  { value: "Charles Schwab Corporation" },
  { value: "Charter Communications" },
  { value: "Chevron" },
  { value: "Chipotle Mexican Grill" },
  { value: "Chubb Limited" },
  { value: "Church & Dwight" },
  { value: "CIGNA" },
  { value: "Cimarex Energy" },
  { value: "Cinnati Financial" },
  { value: "Cintas Corporation" },
  { value: "Cisco Systems" },
  { value: "Citigroup" },
  { value: "Citizens Financial Group" },
  { value: "Citrix Systems" },
  { value: "CME Group" },
  { value: "CMS Energy" },
  { value: "Coca-Cola" },
  { value: "Cognizant Technology Solutions" },
  { value: "Colgate-Palmolive" },
  { value: "Comcast" },
  { value: "Comerica" },
  { value: "Conagra Brands" },
  { value: "Concho Resources" },
  { value: "ConocoPhillips" },
  { value: "Consolidated Edison" },
  { value: "Constellation Brands" },
  { value: "Corning" },
  { value: "Costco Wholesale" },
  { value: "Coty" },
  { value: "Crown Castle International" },
  { value: "CSRA" },
  { value: "CSX" },
  { value: "Cummins" },
  { value: "CVS Health" },
  { value: "D. R. Horton" },
  { value: "Danaher" },
  { value: "Darden Restaurants" },
  { value: "DaVita" },
  { value: "Deere & Co." },
  { value: "Delta Air Lines" },
  { value: "Dentsply Sirona" },
  { value: "Devon Energy" },
  { value: "Digital Realty Trust" },
  { value: "Discover Financial Services" },
  { value: "Discovery" },
  { value: "Dish Network" },
  { value: "Dollar General" },
  { value: "Dollar Tree" },
  { value: "Dominion Energy" },
  { value: "Dover" },
  { value: "DowDuPont" },
  { value: "Dr Pepper Snapple Group" },
  { value: "DTE Energy" },
  { value: "Duke Energy" },
  { value: "Duke Realty" },
  { value: "DXC Technology" },
  { value: "E*Trade" },
  { value: "Eastman Chemical" },
  { value: "Eaton Corporation" },
  { value: "eBay" },
  { value: "Ecolab" },
  { value: "Edison Int'l" },
  { value: "Edwards Lifesciences" },
  { value: "Electronic Arts" },
  { value: "Emerson Electric" },
  { value: "Entergy" },
  { value: "Envision Healthcare" },
  { value: "EOG Resources" },
  { value: "EQT Corporation" },
  { value: "Equifax" },
  { value: "Equinix" },
  { value: "Equity Residential" },
  { value: "Essex Property Trust" },
  { value: "Estee Lauder Cos." },
  { value: "Everest Re Group" },
  { value: "Eversource Energy" },
  { value: "Exelon" },
  { value: "Expedia" },
  { value: "Expeditors International" },
  { value: "Express Scripts" },
  { value: "Extra Space Storage" },
  { value: "Exxon Mobil" },
  { value: "F5 Networks" },
  { value: "Facebook" },
  { value: "Fastenal" },
  { value: "Federal Realty Investment Trust" },
  { value: "FedEx Corporation" },
  { value: "Fidelity National Information Services" },
  { value: "Fifth Third Bancorp" },
  { value: "FirstEnergy" },
  { value: "Fiserv" },
  { value: "FLIR Systems" },
  { value: "Flowserve Corporation" },
  { value: "Fluor" },
  { value: "FMC Corporation" },
  { value: "Foot Locker" },
  { value: "Ford Motor" },
  { value: "Fortive" },
  { value: "Fortune Brands Home & Security" },
  { value: "Franklin Resources" },
  { value: "Freeport-McMoRan" },
  { value: "Gap" },
  { value: "Garmin" },
  { value: "Gartner" },
  { value: "General Dynamics" },
  { value: "General Electric" },
  { value: "General Growth Properties" },
  { value: "General Mills" },
  { value: "General Motors" },
  { value: "Genuine Parts" },
  { value: "Gilead Sciences" },
  { value: "Global Payments" },
  { value: "Goldman Sachs Group" },
  { value: "Goodyear Tire & Rubber" },
  { value: "Grainger (W.W.)" },
  { value: "Halliburton" },
  { value: "Hanesbrands" },
  { value: "Harley-Davidson" },
  { value: "Harris Corporation" },
  { value: "Hartford Financial Svc.Gp." },
  { value: "Hasbro" },
  { value: "HCA Holdings" },
  { value: "HCP" },
  { value: "Helmerich & Payne" },
  { value: "Henry Schein" },
  { value: "Hess Corporation" },
  { value: "Hewlett Packard Enterprise" },
  { value: "Hilton Worldwide Holdings" },
  { value: "Hologic" },
  { value: "Home Depot" },
  { value: "Honeywell Int'l" },
  { value: "Hormel Foods" },
  { value: "Host Hotels & Resorts" },
  { value: "HP" },
  { value: "Humana" },
  { value: "Huntington Bancshares" },
  { value: "Huntington Ingalls Industries" },
  { value: "IDEXX Laboratories" },
  { value: "IHS Markit" },
  { value: "Illinois Tool Works" },
  { value: "Illumina" },
  { value: "Ingersoll-Rand PLC" },
  { value: "Intel" },
  { value: "Intercontinental Exchange" },
  { value: "International Business Machines" },
  { value: "International Paper" },
  { value: "Interpublic Group" },
  { value: "Intl Flavors & Fragrances" },
  { value: "Intuit" },
  { value: "Intuitive Surgical" },
  { value: "Invesco" },
  { value: "IPG Photonics" },
  { value: "IQVIA Holdings" },
  { value: "Iron Mountain orporated" },
  { value: "J. B. Hunt Transport Services" },
  { value: "Jacobs Engineering Group" },
  { value: "JM Smucker" },
  { value: "Johnson & Johnson" },
  { value: "Johnson Controls International" },
  { value: "JPMorgan Chase" },
  { value: "Juniper Networks" },
  { value: "Kansas City Southern" },
  { value: "Kellogg" },
  { value: "KeyCorp" },
  { value: "Kimberly-Clark" },
  { value: "Kimco Realty" },
  { value: "Kinder Morgan" },
  { value: "KLA-Tencor" },
  { value: "Kohl's" },
  { value: "Kraft Heinz" },
  { value: "Kroger" },
  { value: "L Brands" },
  { value: "L-3 Communications Holdings" },
  { value: "Laboratory Corp. of America Holding" },
  { value: "Lam Research" },
  { value: "Leggett & Platt" },
  { value: "Lennar" },
  { value: "Leucadia National" },
  { value: "Lilly (Eli) & Co." },
  { value: "Loln National" },
  { value: "LKQ Corporation" },
  { value: "Lockheed Martin" },
  { value: "Loews" },
  { value: "Lowe's Cos." },
  { value: "LyondellBasell" },
  { value: "M&T Bank" },
  { value: "Macerich" },
  { value: "Macy's" },
  { value: "Marathon Oil" },
  { value: "Marathon Petroleum" },
  { value: "Marriott Int'l." },
  { value: "Marsh & McLennan" },
  { value: "Martin Marietta Materials" },
  { value: "Masco" },
  { value: "Mastercard" },
  { value: "Mattel" },
  { value: "McCormick & Co." },
  { value: "McDonald's" },
  { value: "McKesson" },
  { value: "Medtronic plc" },
  { value: "Merck & Co." },
  { value: "MetLife" },
  { value: "Mettler Toledo" },
  { value: "MGM Resorts International" },
  { value: "Michael Kors Holdings" },
  { value: "Microchip Technology" },
  { value: "Micron Technology" },
  { value: "Microsoft" },
  { value: "Mid-America Apartments" },
  { value: "Mohawk Industries" },
  { value: "Molson Coors Brewing" },
  { value: "Mondelez International" },
  { value: "Monsanto" },
  { value: "Monster Beverage" },
  { value: "Moody's" },
  { value: "Morgan Stanley" },
  { value: "Motorola Solutions" },
  { value: "Mylan N.V." },
  { value: "Nasdaq" },
  { value: "National Oilwell Varco" },
  { value: "Navient" },
  { value: "Nektar Therapeutics" },
  { value: "NetApp" },
  { value: "Netflix" },
  { value: "Newell Brands" },
  { value: "Newfield Exploration" },
  { value: "Newmont Mining Corporation" },
  { value: "News Corp." },
  { value: "NextEra Energy" },
  { value: "Nielsen Holdings" },
  { value: "Nike" },
  { value: "NiSource" },
  { value: "Noble Energy" },
  { value: "Nordstrom" },
  { value: "Norfolk Southern" },
  { value: "Northern Trust" },
  { value: "Northrop Grumman" },
  { value: "Norwegian Cruise Line" },
  { value: "NRG Energy" },
  { value: "Nucor" },
  { value: "Nvidia Corporation" },
  { value: "O'Reilly Automotive" },
  { value: "Occidental Petroleum" },
  { value: "Omnicom Group" },
  { value: "ONEOK" },
  { value: "Oracle" },
  { value: "PACCAR" },
  { value: "Packaging Corporation of America" },
  { value: "Parker-Hannifin" },
  { value: "Paychex" },
  { value: "PayPal" },
  { value: "Pentair" },
  { value: "People's United Financial" },
  { value: "PepsiCo" },
  { value: "PerkinElmer" },
  { value: "Perrigo" },
  { value: "Pfizer" },
  { value: "PG&E" },
  { value: "Philip Morris International" },
  { value: "Phillips 66" },
  { value: "Pinnacle West Capital" },
  { value: "Pioneer Natural Resources" },
  { value: "PNC Financial Services" },
  { value: "Polo Ralph Lauren" },
  { value: "PPG Industries" },
  { value: "PPL" },
  { value: "Praxair" },
  { value: "Pripal Financial Group" },
  { value: "Procter & Gamble" },
  { value: "Progressive" },
  { value: "Prologis" },
  { value: "Prudential Financial" },
  { value: "Public Serv. Enterprise" },
  { value: "Public Storage" },
  { value: "Pulte Homes" },
  { value: "PVH" },
  { value: "Qorvo" },
  { value: "QUALCOMM" },
  { value: "Quanta Services" },
  { value: "Quest Diagnostics" },
  { value: "Range Resources" },
  { value: "Raymond James Financial" },
  { value: "Raytheon" },
  { value: "Realty ome Corporation" },
  { value: "Red Hat" },
  { value: "Regency Centers Corporation" },
  { value: "Regeneron" },
  { value: "Regions Financial" },
  { value: "Republic Services" },
  { value: "ResMed" },
  { value: "Robert Half International" },
  { value: "Rockwell Automation" },
  { value: "Rockwell Collins" },
  { value: "Roper Technologies" },
  { value: "Ross Stores" },
  { value: "Royal Caribbean Cruises" },
  { value: "S&P Global" },
  { value: "Salesforce" },
  { value: "SBA Communications" },
  { value: "SCANA" },
  { value: "Schlumberger" },
  { value: "Seagate Technology" },
  { value: "Sealed Air" },
  { value: "Sempra Energy" },
  { value: "Sherwin-Williams" },
  { value: "Simon Property Group" },
  { value: "Skyworks Solutions" },
  { value: "SL Green Realty" },
  { value: "Snap-On" },
  { value: "Southern" },
  { value: "Southwest Airlines" },
  { value: "Stanley Black & Decker" },
  { value: "Starbucks" },
  { value: "State Street" },
  { value: "Stericycle" },
  { value: "Stryker" },
  { value: "SunTrust Banks" },
  { value: "SVB Financial" },
  { value: "Symantec" },
  { value: "Synchrony Financial" },
  { value: "Synopsys" },
  { value: "Sysco" },
  { value: "T. Rowe Price Group" },
  { value: "Take-Two Interactive" },
  { value: "Tapestry" },
  { value: "Target" },
  { value: "TE Connectivity" },
  { value: "TechnipFMC" },
  { value: "Texas Instruments" },
  { value: "Textron" },
  { value: "The Bank of New York Mellon" },
  { value: "The Clorox" },
  { value: "The Cooper Companies" },
  { value: "The Hershey" },
  { value: "The Mosaic" },
  { value: "The Travelers Companies" },
  { value: "The Walt Disney" },
  { value: "Thermo Fisher Scientific" },
  { value: "Tiffany & Co." },
  { value: "Time Warner" },
  { value: "TJX Companies" },
  { value: "Torchmark" },
  { value: "Total System Services" },
  { value: "Tractor Supply" },
  { value: "TransDigm Group" },
  { value: "TripAdvisor" },
  { value: "Twenty-First Century Fox" },
  { value: "Tyson Foods" },
  { value: "U.S. Bancorp" },
  { value: "UDR" },
  { value: "Ulta Beauty" },
  { value: "Under Armour" },
  { value: "Union Pacific" },
  { value: "United Continental Holdings" },
  { value: "United Health Group" },
  { value: "United Parcel Service" },
  { value: "United Rentals" },
  { value: "United Technologies" },
  { value: "Universal Health Services" },
  { value: "Unum Group" },
  { value: "Valero Energy" },
  { value: "Varian Medical Systems" },
  { value: "Ventas" },
  { value: "Verisign" },
  { value: "Verisk Analytics" },
  { value: "Verizon Communications" },
  { value: "Vertex Pharmaceuticals" },
  { value: "Viacom" },
  { value: "Visa" },
  { value: "Vornado Realty Trust" },
  { value: "Vulcan Materials" },
  { value: "Wal-Mart Stores" },
  { value: "Walgreens Boots Alliance" },
  { value: "Waste Management" },
  { value: "Waters Corporation" },
  { value: "Wec Energy Group" },
  { value: "Wells Fargo" },
  { value: "Welltower" },
  { value: "Western Digital" },
  { value: "Western Union" },
  { value: "WestRock" },
  { value: "Weyerhaeuser" },
  { value: "Whirlpool" },
  { value: "Williams Cos." },
  { value: "Willis Towers Watson" },
  { value: "Wyndham Worldwide" },
  { value: "Wynn Resorts" },
  { value: "Xcel Energy" },
  { value: "Xerox" },
  { value: "Xilinx" },
  { value: "XL Capital" },
  { value: "Xylem" },
  { value: "Yum! Brands" },
  { value: "Zimmer Biomet Holdings" },
  { value: "Zions Bancorp" },
  { value: "Zoetis" },
];

export default Companies;
